---
title: "Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


The numerical function returns a report with 40 models (individual and ensemble, regular learning and deep learning, Python and R). It also returns a number of data visualizations. An example (copy the code to a new file to see it run):

library(Ensembles)
numerical(data = MASS::Boston,
          colnum = 14,
          numresamples = 2,
          how_to_handle_strings = 0,
          do_you_have_new_data = "N",
          save_all_trained_models = "N",
          remove_ensemble_correlations_greater_than = 0.95,
          use_parallel = "Y",
          train_amount = 0.60,
          test_amount = 0.20,
          validation_amount = 0.20)

The classification function returns a report with 25 models (individual and ensemble, regular learning and deep learning, Python and R). It also returns a number of data visualizations. An example (copy the code to a new file to see it run):

library(Ensembles)
classification(data = ISLR::Carseats,
               colnum = 7,
               numresamples = 2,
               do_you_have_new_data = "N",
               how_to_handle_strings = 1,
               save_all_trained_models = "N",
               use_parallel = "N",
               train_amount = 0.60,
               test_amount = 0.20,
               validation_amount = 0.20)
               
The logistic function returns a report with 28 models (individual and ensemble, regular learning and deep learning, Python and R). It also returns a number of data visualizations. An example (copy the code to a new file to see it run):

library(Ensembles)
logistic(data = diabetes,
         colnum = 9,
         numresamples = 2,
         save_all_trained_models = "N",
         how_to_handle_strings = 0,
         do_you_have_new_data = "N",
         remove_ensemble_correlations_greater_than = 0.90,
         use_parallel = "Y",
         train_amount = 0.60,
         test_amount = 0.20,
         validation_amount = 0.20)

The forecasting function returns a report with 27 models (individual and ensemble, regular learning and deep learning, Python and R). It also returns a number of data visualizations. An example (copy the code to a new file to see it run):

library(Ensembles)
forecasting(time_series_data = total_nonfarm,
            train_amount = 0.60,
            number = 3,
            time_interval = "M",
            use_parallel = "Y")
